# snake_ai.py

from typing import List, Tuple, Dict, Optional, Deque, Set, NamedTuple
from collections import deque
import heapq
from functools import lru_cache

# Directions
UP = "up"
DOWN = "down"
LEFT = "left"
RIGHT = "right"

class Position(NamedTuple):
    x: int
    y: int

class SnakeAI:
    def __init__(self, grid_width: int, grid_height: int):
        self.grid_width = grid_width
        self.grid_height = grid_height
        self.directions = [UP, DOWN, LEFT, RIGHT]
        self.opposites = {UP: DOWN, DOWN: UP, LEFT: RIGHT, RIGHT: LEFT}
        
        # State tracking
        self.moves_since_food = 0 # Basic state, could be used by future non-heuristic logic
        self.last_snake_length = 0  # Basic state

        # --- Simplified Tunable Parameters for Cycle-based AI ---
        # Kept for potential simple safety/fallback behavior, not for complex scoring.
        self.recent_history_length = 5
        self.danger_zone_safe_moves_threshold = 1
        # --- End Simplified Tunable Parameters ---
        
        # Initialize Hamiltonian cycle
        self._init_hamiltonian_cycle()

    def _init_hamiltonian_cycle(self):
        """
        Initializes a Hamiltonian path that visits every square in the grid exactly once.
        The path is generated by "snaking" through the grid (boustrophedon order):
        - Even-indexed rows (0, 2, ...): Traversed Left to Right.
        - Odd-indexed rows (1, 3, ...): Traversed Right to Left.

        If grid_height is even, this path naturally forms a Hamiltonian cycle
        (the end of the path is adjacent to the start).
        If grid_height is odd, the generated path is a Hamiltonian path whose ends
        are not necessarily adjacent (depends on grid_width as well), but still covers all cells.
        (Specifically, if height is odd and width is odd, total cells are odd, so a perfect cycle
        connecting back to grid cell (0,0) is impossible for a path starting at (0,0) and
        visiting every cell exactly once. If height is odd and width is even, total cells are even,
        but the snaking pattern might not end adjacent to start).

        Stores the generated path in `self.hamiltonian_cycle` (a List[Position])
        and a mapping from each Position to its index in this path in
        `self.hamiltonian_indices` (a Dict[Position, int]).
        """
        self.hamiltonian_cycle = [] # Ordered list of positions in the cycle
        pos_to_index = {}      # Maps Position(x,y) to its numerical index in the cycle
        
        # Create a basic Hamiltonian cycle that snakes through the grid (boustrophedon order).
        for y in range(self.grid_height):
            # Determine x-coordinates for the current row based on row index parity
            # Even rows (0, 2, ...): traverse Left to Right
            # Odd rows (1, 3, ...): traverse Right to Left
            x_coords = range(self.grid_width) if y % 2 == 0 else range(self.grid_width - 1, -1, -1)
            for x in x_coords:
                pos = Position(x, y)
                # Store the index of this position in the cycle
                pos_to_index[pos] = len(self.hamiltonian_cycle)
                # Add the position to the cycle path
                self.hamiltonian_cycle.append(pos)
        
        self.hamiltonian_indices = pos_to_index

    def _get_valid_moves(self, current_dir: Optional[str]) -> List[str]:
        if not current_dir:
            return self.directions
        return [d for d in self.directions if d != self.opposites[current_dir]]

    # @property
    # def _move_position_cache_size(self): # Associated with self.cache_size which was removed
    #     return self.cache_size           # Keeping lru_cache(maxsize=None) is simpler for now
    
    @lru_cache(maxsize=None)  # Will use instance property
    def _move_position(self, pos: Position, direction: str) -> Position:
        x, y = pos
        moves = {
            UP: Position(x, y - 1),
            DOWN: Position(x, y + 1),
            LEFT: Position(x - 1, y),
            RIGHT: Position(x + 1, y)
        }
        return moves.get(direction, pos)

    def _is_on_grid(self, pos: Position) -> bool:
        return 0 <= pos.x < self.grid_width and 0 <= pos.y < self.grid_height

    def _is_safe(self, pos: Position, snake_body: Tuple[Position, ...]) -> bool:
        return self._is_on_grid(pos) and pos not in snake_body[:-1]

    @lru_cache(maxsize=1024)
    def _manhattan_distance(self, a: Position, b: Position) -> int:
        # This simple heuristic is kept as it might be useful for basic food-seeking
        # or other non-Hamiltonian pathfinding if added later, and has no overhead if not called.
        return abs(a.x - b.x) + abs(a.y - b.y)

    def _follows_hamiltonian(self, pos: Position, prev_pos: Position) -> bool:
        """Check if move follows Hamiltonian cycle direction"""
        try:
            curr_idx = self.hamiltonian_indices[pos]
            prev_idx = self.hamiltonian_indices[prev_pos]
            return (curr_idx == (prev_idx + 1) % len(self.hamiltonian_cycle) or
                   (prev_idx == len(self.hamiltonian_cycle) - 1 and curr_idx == 0))
        except KeyError:
            return False

    def _find_path(self, start: Position, end: Position, 
                   snake_body: Tuple[Position, ...]) -> Optional[List[Position]]:
        obstacles = set(snake_body[1:])
        if end in obstacles:
            obstacles.remove(end)

        open_set = [(self._manhattan_distance(start, end), start)]
        came_from: Dict[Position, Position] = {}
        cost_so_far: Dict[Position, int] = {start: 0}

        while open_set:
            _, current = heapq.heappop(open_set)

            if current == end:
                path = []
                temp = end
                while temp in came_from:
                    path.append(temp)
                    temp = came_from[temp]
                return path[::-1]

            for direction in self.directions:
                neighbor = self._move_position(current, direction)
                
                if not self._is_on_grid(neighbor) or neighbor in obstacles:
                    continue

                new_cost = cost_so_far[current] + 1
                    
                if neighbor not in cost_so_far or new_cost < cost_so_far[neighbor]:
                    cost_so_far[neighbor] = new_cost
                    priority = new_cost + self._manhattan_distance(neighbor, end)
                    heapq.heappush(open_set, (priority, neighbor))
                    came_from[neighbor] = current
        
        return None

    def _flood_fill(self, start_pos: Position, snake_body: Tuple[Position, ...]) -> Tuple[int, float]:
        if not self._is_on_grid(start_pos) or start_pos in snake_body:
            return 0, 0.0
        
        q: Deque[Position] = deque([start_pos])
        visited = {start_pos}
        count = 0
        obstacles = set(snake_body)
        total_freedom_score = 0.0

        while q:
            pos = q.popleft()
            count += 1
            current_cell_freedom = 0
            for direction in self.directions:
                next_pos = self._move_position(pos, direction)
                if self._is_on_grid(next_pos) and next_pos not in obstacles:
                    current_cell_freedom += 1
                    if next_pos not in visited:
                        visited.add(next_pos)
                        q.append(next_pos)
            total_freedom_score += current_cell_freedom
        
        average_freedom = (total_freedom_score / count) if count > 0 else 0.0
        return count, average_freedom

    def _get_direction_from_path(self, head: Position, next_pos: Position) -> str:
        dx = next_pos.x - head.x
        dy = next_pos.y - head.y
        if dx == 1: return RIGHT
        if dx == -1: return LEFT
        if dy == 1: return DOWN
        if dy == -1: return UP
        raise ValueError("Positions are not adjacent")

    # _is_path_a_trap is removed as it was part of the more complex food-seeking logic.
    # The current on-cycle food consumption has a simpler, more direct safety check.

    def _is_dangerous_constriction(self, pos_to_check: Position, entry_direction: str, snake_body_if_moved_to_pos: Tuple[Position, ...]) -> bool:
        # pos_to_check: The cell we're evaluating if it's a constriction.
        # entry_direction: The direction string (UP, DOWN, LEFT, RIGHT) used to enter pos_to_check.
        # snake_body_if_moved_to_pos: The snake's body, assuming its head is now at pos_to_check.
        # This method is kept as it can be useful for basic fallback safety checks,
        # independent of the removed complex scoring heuristics.

        safe_continuing_moves = 0
        # Iterate through all possible directions the snake could move FROM pos_to_check
        for potential_next_direction in self.directions:
            # Prevent the snake from immediately reversing its direction of entry
            if potential_next_direction == self.opposites[entry_direction]:
                continue

            potential_next_pos = self._move_position(pos_to_check, potential_next_direction)

            # A move is safe if it's on the grid and doesn't collide with its own body
            # (excluding the head segment, which is pos_to_check itself).
            # snake_body_if_moved_to_pos[0] is pos_to_check.
            # So, obstacles are snake_body_if_moved_to_pos[1:].
            if self._is_on_grid(potential_next_pos) and \
               potential_next_pos not in snake_body_if_moved_to_pos[1:]:
                safe_continuing_moves += 1

        # If there's X or fewer ways to continue safely, it's a dangerous constriction.
        return safe_continuing_moves <= self.danger_zone_safe_moves_threshold

    # Heuristic scoring (_calculate_... methods) and _evaluate_future_state are removed
    # as the AI now follows a simpler Hamiltonian cycle-based logic.

    def get_best_move(self, snake_body_list: List[Tuple[int, int]],
                      food_pos_tuple: Tuple[int, int],
                      current_direction: Optional[str]) -> str:
        """
        Calculates the best move for the snake, primarily following a Hamiltonian cycle.
        - If on cycle, targets the next position in the cycle.
        - If off cycle, paths towards the start of the cycle (self.hamiltonian_cycle[0]).
        - Includes a placeholder for future food consumption logic.
        - Falls back to basic safe moves if issues arise.

        Args:
            snake_body_list: List of (x, y) tuples representing the snake's body.
            food_pos_tuple: Tuple (x, y) for the food's current position.
                            (Currently used to initialize 'food' object, future use in Step 3).
            current_direction: The snake's current direction of movement. Used for fallbacks.

        Returns:
            A string representing the chosen direction ("up", "down", "left", "right").
        """
        snake_pos = tuple(Position(x, y) for x, y in snake_body_list)
        head = snake_pos[0]
        
        food = Position(*food_pos_tuple) # Food object, will be used in Step 3 food logic
        
        # This will be the position the snake aims for according to the cycle.
        # It might be adjusted by food consumption logic later.
        determined_next_target_on_cycle: Optional[Position] = None

        if head in self.hamiltonian_indices:
            current_idx = self.hamiltonian_indices[head]
            next_idx = (current_idx + 1) % len(self.hamiltonian_cycle)
            determined_next_target_on_cycle = self.hamiltonian_cycle[next_idx]
        else:
            # Snake is off-cycle (e.g., game start). Pathfind to the defined start of the cycle.
            # A more sophisticated version might path to the closest point on the cycle
            # or a point relative to the snake's tail, but this is a simple start.
            path_to_cycle_entry = self._find_path(head, self.hamiltonian_cycle[0], snake_pos)
            if path_to_cycle_entry: # If a path to the cycle start is found
                determined_next_target_on_cycle = path_to_cycle_entry[0]

        # --- Food Consumption Logic ---
        # Default action: chosen_next_pos is whatever determined_next_target_on_cycle was.
        # This means if food is not eaten, snake continues along cycle or path to cycle.
        chosen_next_pos = determined_next_target_on_cycle

        # Only consider eating if the snake's head is currently on the Hamiltonian cycle
        # AND the determined next step on that cycle is where the food is.
        if head in self.hamiltonian_indices and \
           determined_next_target_on_cycle is not None and \
           food == determined_next_target_on_cycle:

            # Simulate eating the food
            # new_head_if_eats will be 'food' (which is determined_next_target_on_cycle)
            simulated_body_after_eating = (food,) + snake_pos # Snake grows

            # Determine the actual next position on the cycle AFTER the food spot
            # Since head is on cycle and food is the next cycle spot, food is on the cycle.
            food_idx_on_cycle = self.hamiltonian_indices[food]
            target_idx_after_food = (food_idx_on_cycle + 1) % len(self.hamiltonian_cycle)
            target_pos_after_food_on_cycle = self.hamiltonian_cycle[target_idx_after_food]

            # Safety Check:
            # 1. The spot on cycle after food must exist and be on the grid.
            # 2. It must not be covered by the snake's new, longer body (excluding the new head at food_pos).
            is_safe_to_eat = (
                self._is_on_grid(target_pos_after_food_on_cycle) and
                target_pos_after_food_on_cycle not in simulated_body_after_eating[1:]
            )
            
            # Optional more robust check (can be added later if needed):
            # Ensure pathability from food_pos to target_pos_after_food_on_cycle
            # with simulated_body_after_eating as obstacles. For now, direct adjacency
            # implied by cycle and the body check is the main concern.

            if is_safe_to_eat:
                # It's safe to eat. The chosen_next_pos becomes the food position.
                chosen_next_pos = food
            # Else: Unsafe to eat. chosen_next_pos remains determined_next_target_on_cycle
            # (the snake will move to the food spot but "ignore" eating it, effectively
            # just following the cycle path). This might seem counter-intuitive but
            # for strict cycle filling, not getting trapped is paramount.
            # A more advanced AI might try a temporary deviation to get the food later.
            # For this version, if unsafe, it just continues on cycle. The food will still be there.

        # --- End Food Consumption Logic ---

        if chosen_next_pos:
            try:
                return self._get_direction_from_path(head, chosen_next_pos)
            except ValueError:
                # This can happen if chosen_next_pos is not adjacent to head,
                # which implies an issue with pathfinding or cycle logic.
                # Fall through to emergency fallback.
                pass

        # Fallback: If no target identified or direction calculation failed.
        # Make any valid move that is not an immediate reversal.
        # (This is a basic fallback; a production system might have more robust error handling here)
        possible_next_moves = self._get_valid_moves(current_direction)
        safe_emergency_moves = []
        for move_option in possible_next_moves:
            test_pos = self._move_position(head, move_option)
            if self._is_safe(test_pos, snake_pos):
                safe_emergency_moves.append(move_option)

        if safe_emergency_moves:
            # Return the first safe emergency move for determinism, or random.choice for variety.
            return safe_emergency_moves[0]
        
        # If truly no safe moves, this implies death is imminent.
        # Return the current direction if available, otherwise default to UP.
        return current_direction if current_direction else UP